// **WEBINAR-CODE* 5-2

export const ENV_VARS = {
    PORT: 'PORT',
    MONGODB_USER: 'MONGODB_USER',
    MONGODB_PASSWORD: 'MONGODB_PASSWORD',
    MONGODB_URL: 'MONGODB_URL',
    MONGODB_DB: 'MONGODB_DB',
    SMTP_HOST:'SMTP_HOST',
    SMTP_PORT:'SMTP_PORT',
    SMTP_USER:'SMTP_USER',
    SMTP_PASSWORD:'MTP_PASSWORD',
};




